version: "3.3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"