export const SET_IMAGE_BUCKETS = "SET_IMAGE_BUCKETS";
export const SET_ALBUM_IMAGE = "SET_ALBUM_IMAGE";
export const SET_ALBUM_LAYOUT = "SET_ALBUM_LAYOUT";
export const SET_NOTIFICATION = "SET_NOTIFICATION";